### ISSUE TITLE
Some quick observations on site

### ISSUE THREAD

**Issue by matentzn** [cell-ontology/cell-ontology.github.io#1]
- Shouldnt the top right Icon by CL icon (instead of OBO) as per website convention to go back to front page?
- Its not ideal that the CL download link points to a raw GitHub URL instead of a purl, but I get way (https [problems](https://github.com/OBOFoundry/purl.obolibrary.org/issues/705)). Imagine we switch to GitHub release due to file sizes.
- The query should redirect to an actual query on ubergraph, e.g.: https://api.triplydb.com/s/eiTP_j7_M
- The favicon should be the CL logo?
- "Ontology Tools Integrated" - could be better: `Integrated in standard ontology tools` (you can also list OAK)
- "Widely Compatible" - (cell ontology has wrong capitalization (consistent Cell Ontology). Also later on the site in "applications"
- Rename "Widely compatible" to "Distributed in standard formats". Also, I would mention that owl (RDF/XML) as this is very important for people using the RDF stack
- I would prefer "Applications" to be "Users" or "Uses" because the word is so ambiguous
- The logo in "direct contact" is skewed
- Cell Ontology Documents should be just "Documentation" or "Developer Documentation"
- Dont know if the link to OBOOK is useful here if it is so general; less is better. The CL documentation should link to OBOOK in the appropriate places
- Same with ODK - all the relevant things for CL are already in the CL documentation
- I would prefer if we do not add a blog. I can already promise to you it will not be maintained and just make us look out of date.
- In footer add link to provide feedback on the website (issue tracker)
- Foundry page in header menu should be "CL in OBO Foundry" or "OBO Foundry Page" or some such. Foundry is not really widely understood

@shawntanzk As always, I don't really insist on anything. Feel free to pick and chose from the feedback and then close the issue. Very well done all!

**Comment by shawntanzk** [comment]
Thanks @matentzn will look into them sometime

**Comment by shawntanzk** [comment]
> Shouldnt the top right Icon by CL icon (instead of OBO) as per website convention to go back to front page?

This was me thinking ahead for template splash page for obo foundry ontologies. We already have a back to top button and we don't have multiple page so I figured that icon would be best used to bring back to obo foundry - that way when distributed widely, it all links to obo foundry. 

> Its not ideal that the CL download link points to a raw GitHub URL instead of a purl, but I get way (https https://github.com/OBOFoundry/purl.obolibrary.org/issues/705). Imagine we switch to GitHub release due to file sizes.

was trying to get it to just download as an owl file, will leave it for now given the issue you mentioned (don't understand it fully but I'm guessing its alright for now)

> The query should redirect to an actual query on ubergraph, e.g.: https://api.triplydb.com/s/eiTP_j7_M

- [ ] To fix

> The favicon should be the CL logo?

- [ ] To fix (thought about this but slipped my mind when doing stuff)

> "Ontology Tools Integrated" - could be better: Integrated in standard ontology tools (you can also list OAK)

- [ ] To fix 

> "Widely Compatible" - (cell ontology has wrong capitalization (consistent Cell Ontology). Also later on the site in "applications"

- [ ] To fix - will scan through all and make sure all are done as Cell Ontology

> Rename "Widely compatible" to "Distributed in standard formats". Also, I would mention that owl (RDF/XML) as this is very important for people using the RDF stack

- [ ] To fix 

> I would prefer "Applications" to be "Users" or "Uses" because the word is so ambiguous

- [ ] To fix 

> The logo in "direct contact" is skewed

- [ ] Will try to fix (not 100% sure I can figure this out cause I'm using their old code and just swapping symbol) 

> Cell Ontology Documents should be just "Documentation" or "Developer Documentation"

- [ ] To fix 

> Dont know if the link to OBOOK is useful here if it is so general; less is better. The CL documentation should link to OBOOK in the appropriate places
> Same with ODK - all the relevant things for CL are already in the CL documentation

- [ ] Will fix, ill be honest, I was just populating things cause i like the footer and it looked empty without stuff LOL 

> I would prefer if we do not add a blog. I can already promise to you it will not be maintained and just make us look out of date.

- [ ] Will remove

> In footer add link to provide feedback on the website (issue tracker)

- [ ] To fix 

> Foundry page in header menu should be "CL in OBO Foundry" or "OBO Foundry Page" or some such. Foundry is not really widely understood

- [ ] To fix
